
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - node.harvesterci.io
  resources:
  - registers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node.harvesterci.io
  resources:
  - registers/status
  verbs:
  - get
  - patch
  - update
