apiVersion: node.harvesterci.io/v1alpha1
kind: Register
metadata:
  name: node2
spec:
  macAddress: "0c:c4:7a:6b:80:d0"
  token: token
  address: 172.16.128.11
  netmask: 255.255.248.0
  gateway: 172.16.128.1
  pxeIsoURL: http://172.16.135.50:8080/v1.0.0/harvester-v1.0.0-amd64.iso
  imageURL: http://172.16.135.50:8080
  slug: "harvester_1_0_0"
  kernelBootArguments: "ip=enp0s20f0:dhcp" #workaround to address https://github.com/harvester/harvester/issues/1363
