apiVersion: node.harvesterci.io/v1alpha1
kind: Register
metadata:
  name: node2
spec:
  # Add fields here
  macAddress: "0c:c4:7a:6b:80:d0"
  token: token
  interface: eth0
  harvesterIsoURL: http://172.16.132.186:8080/harvester-amd64.iso
  address: 172.16.128.11
  netmask: 255.255.248.0
  gateway: 172.16.128.1
