{{ if .Values.tinkInstall }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: db
          image: {{ .Values.images.db }}
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - tinkerbell
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          name: db
          ports:
            - containerPort: 5432
              name: psql
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - tinkerbell
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: psql
      port: 5432
      targetPort: psql
  selector:
    app: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}